env: "gymma_vec"

env_args:
  key: vmas.gym:VMASFootball-2-v0
  time_limit: 1024
  pretrained_wrapper: null

test_greedy: True
test_nepisode: 256
test_interval: 1_400_000
log_interval: 1_400_000
runner_log_interval: 1_400_000
learner_log_interval: 1_400_000
t_max: 140_000_000
batch_size_run: 256
